### ISSUE TITLE
Crash with old MKS Plugin

### ISSUE THREAD

**Issue by Toylerrr** [Toylerrr/ELEGOO_Neptune2_Cura#1]
The MKS plugin that is included with Elegoo_cura seems to have an error when closing.

Code below
Traceback (most recent call last):
  File "C:\Users\ultimaker\AppData\Local\Temp\cura-build-4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085, in event
  File "C:\Users\ultimaker\AppData\Local\Temp\cura-build-4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469, in event
  File "C:\Users\ultimaker\AppData\Local\Temp\cura-build-4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218, in call
  File "C:\Users\ultimaker\AppData\Local\Temp\cura-build-4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 614, in closeApplication
  File "C:\Users\ultimaker\AppData\Local\Temp\cura-build-4.9-exe\build\inst\lib\python3.8\site-packages\cura\Settings\MachineManager.py", line 317, in setActiveMachine
  File "C:\Users\ultimaker\AppData\Local\Temp\cura-build-4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 670, in setGlobalContainerStack
  File "C:\Users\ultimaker\AppData\Local\Temp\cura-build-4.9-exe\build\inst\lib\python3.8\site-packages\UM\Application.py", line 281, in setGlobalContainerStack
  File "C:\Users\ultimaker\AppData\Local\Temp\cura-build-4.9-exe\build\inst\lib\python3.8\site-packages\UM\Signal.py", line 219, in emit
  File "C:\Users\ultimaker\AppData\Local\Temp\cura-build-4.9-exe\build\inst\lib\python3.8\site-packages\UM\Signal.py", line 332, in __performEmit
  File "C:\Users\tyler\AppData\Roaming\cura\4.9\plugins\MKS Plugin\MKSOutputDevicePlugin.py", line 136, in reCheckConnections
    Logger.log("d", "GlobalContainerStack change %s" % active_machine.getMetaDataEntry("mks_network_key"))
AttributeError: 'NoneType' object has no attribute 'getMetaDataEntry'

**Comment by Toylerrr** [comment]
Fixed updated to new MKS Wifi plugin and use this fix to get it to output photos

https://github.com/Jeredian/mks-wifi-plugin/issues/142#issuecomment-804674918
